### PR TITLE
Support multiline as a polymer attribute

### PR DESCRIPTION
**Pull request by alex-deaconu**
## Description
Support multiline as a polymer attribute

Use reflectToAttribute: true to reflect the
value back on the attribute

Use String variable for multiline attribute
Boolean variable interprets attribute existence
not its value

Update package.json version and package-lock

## Motivation and Context
Playlist Epic

## How Has This Been Tested?
Tested locally via proxy. Updated unit tests. e2e tests pass.

## Release Plan:
- As the Submitter, upon requesting review of this pull request, I confirm that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed. 
- As the Reviewer, upon approving the changes in this PR, I confirm I have reviewed and I agree that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed

#### Release Checklist Items Skipped?
No

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@ezequielc please review. Thanks!

**Review by ezequielc — APPROVED** [review]
@alex-deaconu Looks good 👍

**Comment by alex-deaconu** [comment]
@stulees @olegrise we found an issue with setting the `multiline` attribute via the attribute-data. Basically, it doesn't work. This is because the attribute being set in polymer does not update it on the `rise-text` element, and the css selector doesn't work.

As a fix, we're setting `reflectToAttribute: true` ([link](https://polymer-library.polymer-project.org/3.0/docs/devguide/properties#attribute-reflection)). This updates the attribute on the element itself. However, there is a problem, because a Boolean attribute can either be there, or not. This means that `multiline="false"` is interpreted as `true`. Also, the Boolean attribute is represented in the HTML as just the attribute `multiline` instead of `multiline="true"`. This is done automatically by Polymer.

To address this, we updated the property to String, and are now supporting both `"true"` String values which are set via the html attribute, and `true` boolean values which are set from the Template Editor. Also, checked `false` and `"false"` are handled correctly.

Please review. Thanks!

**Comment by olegrise** [comment]
Interesting and good to know. Thanks.

**Pull request merged**
